name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write # for setup-goproxy
  contents: read
  packages: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Build and test
        run: |
          go build
          go test -v ./...