name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write # for setup-goproxy
  contents: read
  packages: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: OIDC Setup for goproxy
        uses: github/setup-goproxy@v1.1.0

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Build and test
        run: |
          go build
          go test -v ./...